export const affirmations: string[] = [
  "You are capable of achieving your goals.",
  "Every small step brings you closer to success.",
  "Stay focused and keep pushing forward!",
  "Believe in yourself, your time is coming.",
  "Success is a journey, not a destination.",
  "You have the skills and determination to succeed.",
  "Opportunities are everywhere if you remain open.",
  "Your efforts will pay off, stay consistent.",
  "Every day brings new chances to grow.",
  "Be patient with yourself; great things take time.",
  "You are stronger than any challenge you face.",
  "Trust the process, and the results will come.",
  "Your potential is limitless, embrace it.",
  "Failure is a stepping stone to success.",
  "You deserve every good thing coming your way.",
  "Keep showing up, your breakthrough is near.",
  "Your hard work is building a brighter future.",
  "You are in charge of your own success.",
  "Challenges are opportunities in disguise.",
  "You bring unique value to the table.",
  "The right opportunity is aligning for you.",
  "You have the power to create your dream life.",
  "Every rejection is redirection toward something better.",
  "Your persistence will unlock doors.",
  "You are worthy of the success you seek.",
  "Great things take time, and you're on your way.",
  "Your skills and talents are needed in the world.",
  "Stay optimistic; the best is yet to come.",
  "You are resourceful and creative in finding solutions.",
  "Success is within your reach; keep going.",
  "You have everything you need to succeed.",
  "Trust yourself; you are capable of amazing things.",
  "Each day is an opportunity to move forward.",
  "You are brave for pursuing your dreams.",
  "The universe is working in your favor.",
  "Believe in your power to shape your destiny.",
  "You are open to new and exciting possibilities.",
  "Your determination will lead you to success.",
  "You grow stronger and wiser every day.",
  "You are resilient, and nothing can hold you back.",
  "Your positive mindset attracts opportunities.",
  "Success is a journey, and you're on the right path.",
  "You are building a life you're proud of.",
  "Stay focused; your efforts are making a difference.",
  "You can overcome any obstacle in your way.",
  "The right doors will open for you at the right time.",
  "Every challenge helps you grow and improve.",
  "You are creating the career and life you desire.",
  "Your energy and attitude create your opportunities.",
  "Keep going; you are closer than you think.",
  "Your dreams are valid and worth pursuing.",
  "Every day brings you closer to your goals.",
  "You are adaptable and open to change.",
  "The right job will find its way to you.",
  "Believe in the power of your unique story.",
  "You are enough just as you are.",
  "Your confidence shines through in every interaction.",
  "You are exactly where you need to be.",
  "Your courage to keep going will pay off.",
  "You attract abundance and success effortlessly.",
  "You are prepared and ready for new opportunities.",
  "Your work and efforts matter deeply.",
  "You are destined for greatness.",
  "Each step forward is progress, no matter how small.",
  "You have the power to overcome any limitation.",
  "Every experience prepares you for what's next.",
  "The best is yet to come for you.",
  "You are worthy of love, success, and happiness.",
  "You are a magnet for amazing opportunities.",
  "Believe in your ability to create positive change.",
  "Your persistence and patience will pay off.",
  "You are creating a life filled with purpose.",
  "You are worthy of achieving your wildest dreams.",
  "The journey is just as important as the destination.",
  "Every job application brings you closer to your dream role.",
  "You have unique gifts to share with the world.",
  "You are capable of handling whatever comes your way.",
  "Every day is a fresh start with endless possibilities.",
  "You have the courage to pursue what sets your soul on fire.",
  "Opportunities are drawn to your hard work and passion.",
  "You are a strong and capable person.",
  "Your dream job is waiting for you.",
  "The world is better because of your talents.",
  "You have a bright future ahead of you.",
  "Challenges make you stronger and wiser.",
  "You deserve success and are worthy of achieving it.",
  "Believe in the person you are becoming.",
  "You are making a positive impact on the world.",
  "Keep pushing forward; you're doing amazing work.",
  "You are unstoppable when you set your mind to something.",
  "The right opportunity will come when you least expect it.",
  "You are constantly growing and evolving.",
  "Your optimism attracts the right people and situations.",
  "You are in the process of creating a fulfilling career.",
  "Every action you take moves you closer to your goals.",
  "You are capable of learning and adapting to any challenge.",
  "Your mindset is your greatest strength.",
  "You deserve to feel confident and proud of your journey.",
  "The right opportunities will come to you at the right time.",
  "Stay focused and trust the process of growth.",
  "Your perseverance will lead you to your dream job.",
  "You are capable of turning challenges into opportunities.",
  "Every experience is a lesson that moves you forward.",
  "You have everything within you to succeed.",
  "Keep going; the finish line is closer than you think.",
  "Your passion and dedication inspire others.",
  "You are resilient and rise above every challenge.",
  "The journey may be tough, but the rewards are worth it.",
  "Trust that the universe has a plan for you.",
  "You are an asset to any team or organization.",
  "Great opportunities are headed your way.",
  "You are capable of more than you can imagine.",
  "Success is built on consistent effort over time.",
  "You are creating a positive impact in the world.",
  "Your confidence grows with every challenge you face.",
  "You have the ability to achieve your biggest dreams.",
  "Your unique skills and talents make you valuable.",
  "You are deserving of all the success you desire.",
  "Keep moving forward; you're on the path to greatness.",
  "Believe in your ability to make things happen.",
  "You are capable of thriving in any environment.",
  "Your future is bright and filled with possibility.",
  "You have the power to create the life you want.",
  "Success flows naturally to you.",
  "Your dedication and focus will lead you to success.",
  "You are worthy of achieving your goals and dreams.",
  "Stay positive; good things are coming your way.",
  "You have the strength to overcome any adversity.",
  "Every day, you are one step closer to your dream.",
  "You are powerful and unstoppable.",
];
